//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CongVan
    {
        public int IdCongVan { get; set; }
        public string TenCongVan { get; set; }
        public byte[] FileCongVan { get; set; }
    }
}
