//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KL
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        public int IdNhanVien { get; set; }
        public string TenNhanVien { get; set; }
        public Nullable<int> Tuoi { get; set; }
        public string DiaChi { get; set; }
    }
}
